# Hello Pod1 configuration
apiVersion: v1
kind: Pod
metadata:
  name: hello-pod1
  namespace: development
  labels:
    app: hello-pod1
spec:
  containers:
  - name: hello-container
    image: murali383/hello-service
    
# Hello Pod2 configuration
apiVersion: v1
kind: Pod
metadata:
  name: hello-pod2
  namespace: development
  labels:
    app: hello-pod1
spec:
  containers:
  - name: hello-container
    image: murali383/hello-service
    
# Hello Service1 configuration
kind: Service
apiVersion: v1
metadata:
  name: hello-service1
  namespace: development
spec:
  selector:
    app: hello-pod1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    
# Hello Service2 configuration
kind: Service
apiVersion: v1
metadata:
  name: hello-service2
  namespace: development
spec:
  selector:
    app: hello-pod2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    
# Google Service configuration
#kind: Service
#apiVersion: v1
#metadata:
#  name: google-service
#  namespace: development
#spec:
#  type: ExternalName
#  externalName: www.google.com
